# Generated by Django 6.0.7 on 2026-07-11 06:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('zerodha', 'Zerodha'), ('uplink', 'Uplink'), ('angel', 'Angel Broking'), ('coindcx', 'CoinDCX'), ('delta', 'Delta Exchange')], max_length=100, unique=True)),
                ('api_key', models.CharField(max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('access_token_updated_at', models.DateTimeField(blank=True, help_text='Timestamp of when the access token was last updated', null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_id', models.CharField(blank=True, help_text='Customer ID provided by the broker', max_length=150, null=True)),
                ('redirect_url', models.URLField(blank=True, help_text="Redirect URL for the broker's API authentication flow", max_length=500, null=True)),
                ('base_redirect_url', models.URLField(blank=True, help_text='Base URL used for OAuth redirect in the API authentication', max_length=500, null=True)),
                ('api_endpoint', models.URLField(blank=True, help_text='API endpoint URL for the broker', max_length=500, null=True)),
                ('enable_trade', models.BooleanField(default=False, help_text='Enable or disable trading functionality for this broker')),
                ('enable_websocket', models.BooleanField(default=False, help_text='Enable or disable websocket connection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedTickStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kalai.broker')),
            ],
        ),
        migrations.CreateModel(
            name='AlgoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(default='none', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tabledata', models.JSONField(blank=True, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalai.broker')),
            ],
            options={
                'indexes': [models.Index(fields=['broker', 'tablename'], name='kalai_algoi_broker__2a0b6b_idx')],
                'unique_together': {('broker', 'tablename')},
            },
        ),
    ]
