# Generated by Django 6.0.7 on 2026-07-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key for generating active OTPs', max_length=255, null=True),
        ),
    ]
