# Generated by Django 6.0.7 on 2026-07-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0002_broker_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='access_token_required',
            field=models.BooleanField(default=False, help_text='Require a daily access token to establish websocket connection'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='name',
            field=models.CharField(choices=[('zerodha', 'Zerodha'), ('uplink', 'Uplink'), ('angel', 'Angel Broking'), ('coindcx', 'CoinDCX'), ('delta', 'Delta Exchange'), ('tradovate', 'Tradovate')], max_length=100, unique=True),
        ),
    ]
