# Generated by Django 6.0.7 on 2026-07-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0006_remove_broker_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.RemoveIndex(
            model_name='algoinfo',
            name='kalai_algoi_broker__2a0b6b_idx',
        ),
        migrations.AddField(
            model_name='broker',
            name='enable_schedule',
            field=models.BooleanField(default=False, help_text='Enable time-based automatic start/stop schedule for WebSocket'),
        ),
        migrations.AddField(
            model_name='broker',
            name='ws_operating_days',
            field=models.CharField(default='MON,TUE,WED,THU,FRI', help_text='Comma-separated operating days (e.g. MON,TUE,WED,THU,FRI or ALL)', max_length=50),
        ),
        migrations.AddField(
            model_name='broker',
            name='ws_start_time',
            field=models.TimeField(blank=True, help_text='Daily start time for WebSocket (e.g. 08:45:00)', null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='ws_stop_time',
            field=models.TimeField(blank=True, help_text='Daily stop time for WebSocket (e.g. 15:35:00)', null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='enable_trade',
            field=models.BooleanField(default=False, help_text='Enable or disable trading functionality for this account'),
        ),
        migrations.AddIndex(
            model_name='algoinfo',
            index=models.Index(fields=['account', 'tablename'], name='kalai_algoi_account_5bd418_idx'),
        ),
        migrations.AlterModelTable(
            name='broker',
            table='kalai_broker',
        ),
    ]
