# Generated by Django 6.0.7 on 2026-07-25 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0007_alter_broker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='ws_operating_days',
            field=models.CharField(default='ALL', help_text='Comma-separated operating days (default: ALL)', max_length=50),
        ),
        migrations.AlterField(
            model_name='broker',
            name='ws_start_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), help_text='Daily start time for WebSocket (default: 00:00:00)', null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='ws_stop_time',
            field=models.TimeField(blank=True, default=datetime.time(23, 59, 59), help_text='Daily stop time for WebSocket (default: 23:59:59)', null=True),
        ),
    ]
