# Generated by Django 6.0.7 on 2026-07-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0008_alter_broker_ws_operating_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='enable_schedule',
            field=models.BooleanField(default=True, help_text='Enable time-based automatic start/stop schedule for WebSocket'),
        ),
    ]
