# Generated by Django 6.0.7 on 2026-07-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0009_alter_broker_enable_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='ws_operating_days',
            field=models.CharField(choices=[('WEEKDAYS', 'Weekdays (Mon-Fri)'), ('ALL', 'All Days')], default='ALL', help_text='Select operating days for WebSocket schedule', max_length=50),
        ),
    ]
