# Generated by Django 6.1 on 2026-08-21 16:30

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0012_add_kotak_neo_broker_and_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_name', models.CharField(db_index=True, default='zerodha_opt', help_text='Algorithm identifier', max_length=100)),
                ('tag', models.CharField(db_index=True, default='GENERAL', help_text='Category tag (e.g. GENERAL, TRADE, STRIKE, PERF)', max_length=50)),
                ('level', models.CharField(db_index=True, default='INFO', help_text='Log level (INFO, WARNING, ERROR)', max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Algorithm Log',
                'verbose_name_plural': 'Algorithm Logs',
                'db_table': 'kalai_algolog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='algoinfo',
            name='kalai_algoi_account_5bd418_idx',
        ),
        migrations.AlterUniqueTogether(
            name='algoinfo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='broker',
            name='ws_start_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), help_text='Daily start time for WebSocket/Algo (default: 09:00:00)', null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='ws_stop_time',
            field=models.TimeField(blank=True, default=datetime.time(23, 55), help_text='Daily stop time for WebSocket/Algo (default: 23:55:00)', null=True),
        ),
        migrations.AddField(
            model_name='algolog',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='algo_logs', to='kalai.broker'),
        ),
        migrations.AddIndex(
            model_name='algolog',
            index=models.Index(fields=['-timestamp'], name='kalai_algol_timesta_f20bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='algolog',
            index=models.Index(fields=['account', '-timestamp'], name='kalai_algol_account_176276_idx'),
        ),
        migrations.AddIndex(
            model_name='algolog',
            index=models.Index(fields=['tag', '-timestamp'], name='kalai_algol_tag_3c8378_idx'),
        ),
        migrations.AddIndex(
            model_name='algolog',
            index=models.Index(fields=['level', '-timestamp'], name='kalai_algol_level_fb0ac1_idx'),
        ),
    ]
