# Generated by Django 6.1 on 2026-08-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0014_add_coinswitch_broker_and_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algoinfo',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kalai.broker'),
        ),
        migrations.AlterField(
            model_name='algolog',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='algo_logs', to='kalai.broker'),
        ),
        migrations.AlterField(
            model_name='processedtickstore',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kalai.broker'),
        ),
    ]
