# Generated by Django 6.1 on 2026-08-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0015_alter_algoinfo_account_alter_algolog_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='api_endpoint',
            field=models.TextField(blank=True, help_text='API endpoint URL for the broker', null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='api_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='base_redirect_url',
            field=models.TextField(blank=True, help_text='Base URL used for OAuth redirect in the API authentication', null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='redirect_url',
            field=models.TextField(blank=True, help_text="Redirect URL for the broker's API authentication flow", null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
