# Generated by Django 6.1 on 2026-08-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0016_alter_broker_access_token_alter_broker_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algoinfo',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Algo State / Table', 'verbose_name_plural': 'Algo State / Tables'},
        ),
        migrations.AlterField(
            model_name='algoinfo',
            name='tablename',
            field=models.CharField(db_index=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='algoinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='algoinfo',
            index=models.Index(fields=['account', 'tablename'], name='kalai_algoi_account_5bd418_idx'),
        ),
        migrations.AddIndex(
            model_name='algoinfo',
            index=models.Index(fields=['tablename'], name='kalai_algoi_tablena_007992_idx'),
        ),
        migrations.AddIndex(
            model_name='algoinfo',
            index=models.Index(fields=['-timestamp'], name='kalai_algoi_timesta_69f0dd_idx'),
        ),
        migrations.AlterModelTable(
            name='algoinfo',
            table='kalai_algoinfo',
        ),
    ]
