# Generated by Django 6.1 on 2026-08-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0017_alter_algoinfo_options_alter_algoinfo_tablename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algoinfo',
            options={'ordering': ['-is_pinned', '-timestamp'], 'verbose_name': 'Algo State / Table', 'verbose_name_plural': 'Algo State / Tables'},
        ),
        migrations.AddField(
            model_name='algoinfo',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, help_text='Pin this table to the top of the admin changelist'),
        ),
        migrations.AddIndex(
            model_name='algoinfo',
            index=models.Index(fields=['-is_pinned', '-timestamp'], name='kalai_algoi_is_pinn_014d49_idx'),
        ),
    ]
