# Generated by Django 6.1 on 2026-08-30 03:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0018_alter_algoinfo_options_algoinfo_is_pinned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradingsymbol', models.CharField(db_index=True, max_length=100)),
                ('instrument_token', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('product', models.CharField(default='NRML', help_text='Product type: NRML, MIS, CNC, FUT, SPOT', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='Net active quantity (positive for Long, negative for Short, 0 for Closed)', max_digits=18)),
                ('buy_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('buy_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('buy_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('sell_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('sell_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('sell_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('last_price', models.DecimalField(decimal_places=4, default=0, help_text='Last Traded Price (LTP)', max_digits=18)),
                ('unrealized_pnl', models.DecimalField(decimal_places=4, default=0, help_text='Unrealized M2M profit/loss', max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=4, default=0, help_text='Realized booked profit/loss', max_digits=18)),
                ('total_pnl', models.DecimalField(decimal_places=4, default=0, help_text='Total profit/loss (Realized + Unrealized)', max_digits=18)),
                ('is_open', models.BooleanField(db_index=True, default=True, help_text='True if net quantity != 0')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='kalai.broker')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'kalai_brokerposition',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['account', 'is_open'], name='kalai_broke_account_eb5224_idx'), models.Index(fields=['tradingsymbol'], name='kalai_broke_trading_bdfcff_idx'), models.Index(fields=['-updated_at'], name='kalai_broke_updated_1dfd35_idx')],
                'unique_together': {('account', 'tradingsymbol', 'product')},
            },
        ),
        migrations.CreateModel(
            name='DailyPnLSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('realized_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('unrealized_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('net_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('turnover', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_pnl_snapshots', to='kalai.broker')),
            ],
            options={
                'verbose_name': 'Daily P&L Snapshot',
                'verbose_name_plural': 'Daily P&L Snapshots',
                'db_table': 'kalai_dailypnlsnapshot',
                'ordering': ['-date', 'account'],
                'indexes': [models.Index(fields=['account', '-date'], name='kalai_daily_account_1a3c61_idx'), models.Index(fields=['-date'], name='kalai_daily_date_4de7bd_idx')],
                'unique_together': {('account', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('tradingsymbol', models.CharField(db_index=True, max_length=100)),
                ('product', models.CharField(default='NRML', max_length=50)),
                ('action_type', models.CharField(default='BUY', help_text='BUY, SELL, STOP_LOSS, SQUARE_OFF', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('executed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_records', to='kalai.broker')),
            ],
            options={
                'verbose_name': 'Trade Record',
                'verbose_name_plural': 'Trade Records',
                'db_table': 'kalai_traderecord',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['account', '-executed_at'], name='kalai_trade_account_ab695d_idx'), models.Index(fields=['tradingsymbol', '-executed_at'], name='kalai_trade_trading_4f2d06_idx'), models.Index(fields=['-executed_at'], name='kalai_trade_execute_2bd307_idx')],
            },
        ),
    ]
