# Generated by Django 6.1 on 2026-08-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0019_brokerposition_dailypnlsnapshot_traderecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='api_secret_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the API Secret was last created or updated', null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='secret_key_validity_days',
            field=models.PositiveIntegerField(default=90, help_text='Secret key validity duration in days (default: 90 for CoinSwitch)'),
        ),
        migrations.AddField(
            model_name='broker',
            name='secret_key_warn_days',
            field=models.PositiveIntegerField(default=7, help_text='Days before expiry to trigger warning notifications (default: 7 days)'),
        ),
    ]
