# Generated by Django on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0020_broker_api_secret_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='enable_secret_key_expiry',
            field=models.BooleanField(
                default=False,
                help_text='Enable secret key validity tracking and expiry alerts for this account (e.g. CoinSwitch 90-day expiry)'
            ),
        ),
    ]
