# Generated by Django 6.1 on 2026-08-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0021_broker_enable_secret_key_expiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedtickstore',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Processed Tick Store', 'verbose_name_plural': 'Processed Tick Stores'},
        ),
        migrations.AddIndex(
            model_name='processedtickstore',
            index=models.Index(fields=['account', '-timestamp'], name='kalai_proce_account_eb30c6_idx'),
        ),
        migrations.AddIndex(
            model_name='processedtickstore',
            index=models.Index(fields=['account', 'timestamp'], name='kalai_proce_account_6cc742_idx'),
        ),
        migrations.AddIndex(
            model_name='processedtickstore',
            index=models.Index(fields=['-timestamp'], name='kalai_proce_timesta_796de5_idx'),
        ),
        migrations.AlterModelTable(
            name='processedtickstore',
            table='kalai_processedtickstore',
        ),
    ]
