# Generated by Django 6.1 on 2026-08-31 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalai', '0022_alter_processedtickstore_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(db_index=True, default='cum_table', help_text='e.g. cum_table, aug_table, coindcx_market_details', max_length=100)),
                ('row_count', models.IntegerField(default=0, help_text='Number of contracts/rows stored')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tabledata', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_masters', to='kalai.broker')),
            ],
            options={
                'verbose_name': 'Exchange Master Data',
                'verbose_name_plural': 'Exchange Master Data',
                'db_table': 'kalai_exchangemaster',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['account', 'master_name'], name='kalai_excha_account_255348_idx'), models.Index(fields=['master_name'], name='kalai_excha_master__7f3e0c_idx'), models.Index(fields=['-updated_at'], name='kalai_excha_updated_97abf8_idx')],
            },
        ),
    ]
